################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
C_SRCS := 
CPP_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
uavcan/libuavcan_drivers/stm32/test_stm32f107/src/sys \
uavcan/libuavcan_drivers/stm32/test_stm32f107/src \
uavcan/libuavcan_drivers/stm32/driver/src \
uavcan/libuavcan_drivers/lpc11c24/test_olimex_lpc_p11c24/src/sys \
uavcan/libuavcan_drivers/lpc11c24/test_olimex_lpc_p11c24/src \
uavcan/libuavcan_drivers/lpc11c24/test_olimex_lpc_p11c24/lpc_chip_11cxx_lib/src \
uavcan/libuavcan_drivers/lpc11c24/driver/src \
uavcan/libuavcan_drivers/linux/apps \
uavcan/libuavcan/tools \
uavcan/libuavcan/test/util \
uavcan/libuavcan/test/transport \
uavcan/libuavcan/test/transport/can \
uavcan/libuavcan/test \
uavcan/libuavcan/test/protocol \
uavcan/libuavcan/test/node \
uavcan/libuavcan/test/marshal \
uavcan/libuavcan/test/helpers \
uavcan/libuavcan/test/dsdl_test \
uavcan/libuavcan/src \
uavcan/libuavcan/src/transport \
uavcan/libuavcan/src/protocol \
uavcan/libuavcan/src/node \
uavcan/libuavcan/src/marshal \
uavcan/libuavcan/src/driver \
src/systemcmds/ver \
src/systemcmds/top \
src/systemcmds/tests \
src/systemcmds/reboot \
src/systemcmds/pwm \
src/systemcmds/preflight_check \
src/systemcmds/perf \
src/systemcmds/param \
src/systemcmds/nshterm \
src/systemcmds/mtd \
src/systemcmds/mixer \
src/systemcmds/i2c \
src/systemcmds/esc_calib \
src/systemcmds/dumpfile \
src/systemcmds/config \
src/systemcmds/boardinfo \
src/systemcmds/bl_update \
src/modules/unit_test \
src/modules/uavcan \
src/modules/uavcan/sensors \
src/modules/uavcan/actuators \
src/modules/uORB \
src/modules/systemlib \
src/modules/systemlib/pwm_limit \
src/modules/systemlib/pid \
src/modules/systemlib/param \
src/modules/systemlib/mixer \
src/modules/systemlib/bson \
src/modules/sensors \
src/modules/segway \
src/modules/sdlog2 \
src/modules/px4iofirmware \
src/modules/position_estimator_inav \
src/modules/path_planning \
src/modules/path_planning/parser_sensorboard \
src/modules/path_planning/mission \
src/modules/path_planning/kalman_tracker \
src/modules/parser_200WX \
src/modules/navigator \
src/modules/mission_planning \
src/modules/mc_pos_control \
src/modules/mc_att_control \
src/modules/mavlink/mavlink_tests \
src/modules/mavlink \
src/modules/gpio_led \
src/modules/fw_pos_control_l1/mtecs \
src/modules/fw_pos_control_l1 \
src/modules/fw_att_control \
src/modules/fixedwing_backside \
src/modules/ekf_att_pos_estimator \
src/modules/dataman \
src/modules/controllib/uorb \
src/modules/controllib \
src/modules/controllib/block \
src/modules/commander \
src/modules/commander/commander_tests \
src/modules/bottle_drop \
src/modules/autonomous_sailing \
src/modules/autonomous_sailing/mpcForces \
src/modules/attitude_estimator_so3 \
src/modules/attitude_estimator_ekf/codegen \
src/modules/attitude_estimator_ekf \
src/lib/rc \
src/lib/mathlib/math/test \
src/lib/mathlib/math/filter \
src/lib/mathlib/math \
src/lib/launchdetection \
src/lib/geo_lookup \
src/lib/geo \
src/lib/external_lgpl/tecs \
src/lib/ecl/l1 \
src/lib/ecl/attitude_fw \
src/lib/conversion \
src/examples/px4_simple_app \
src/examples/px4_mavlink_debug \
src/examples/px4_daemon_app \
src/examples/matlab_csv_serial \
src/examples/math_demo \
src/examples/hwtest \
src/examples/flow_speed_control \
src/examples/flow_position_estimator \
src/examples/fixedwing_control \
src/drivers/stm32/tone_alarm \
src/drivers/stm32 \
src/drivers/stm32/adc \
src/drivers/sf0x \
src/drivers/roboclaw \
src/drivers/rgbled \
src/drivers/px4io \
src/drivers/px4fmu \
src/drivers/px4flow \
src/drivers/pca9685 \
src/drivers/pca8574 \
src/drivers/ms5611 \
src/drivers/mpu6000 \
src/drivers/mkblctrl \
src/drivers/meas_airspeed \
src/drivers/md25 \
src/drivers/mb12xx \
src/drivers/lsm303d \
src/drivers/ll40ls \
src/drivers/led \
src/drivers/l3gd20 \
src/drivers/hott \
src/drivers/hott/hott_telemetry \
src/drivers/hott/hott_sensors \
src/drivers/hmc5883 \
src/drivers/hil \
src/drivers/gps \
src/drivers/frsky_telemetry \
src/drivers/ets_airspeed \
src/drivers/device \
src/drivers/boards/px4io-v2 \
src/drivers/boards/px4io-v1 \
src/drivers/boards/px4fmu-v2 \
src/drivers/boards/px4fmu-v1 \
src/drivers/boards/aerocore \
src/drivers/bma180 \
src/drivers/blinkm \
src/drivers/ardrone_interface \
src/drivers/airspeed \
platforms \
nuttx-configs/px4io-v2/src \
nuttx-configs/px4io-v1/src \
nuttx-configs/px4fmu-v2/src \
nuttx-configs/px4fmu-v1/src \
nuttx-configs/aerocore/src \
Tools/tests-host \
NuttX/nuttx/tools/pic32mx \
NuttX/nuttx/tools \
NuttX/nuttx/syscall \
NuttX/nuttx/sched \
NuttX/nuttx/net/uip \
NuttX/nuttx/net \
NuttX/nuttx/mm \
NuttX/nuttx/mm/bin \
NuttX/nuttx/libxx \
NuttX/nuttx/libc/wqueue \
NuttX/nuttx/libc/unistd \
NuttX/nuttx/libc/time \
NuttX/nuttx/libc/termios \
NuttX/nuttx/libc/string \
NuttX/nuttx/libc/stdlib \
NuttX/nuttx/libc/stdio \
NuttX/nuttx/libc/spawn \
NuttX/nuttx/libc/signal \
NuttX/nuttx/libc/semaphore \
NuttX/nuttx/libc/sched \
NuttX/nuttx/libc/queue \
NuttX/nuttx/libc/pthread \
NuttX/nuttx/libc/net \
NuttX/nuttx/libc/mqueue \
NuttX/nuttx/libc/misc \
NuttX/nuttx/libc/math \
NuttX/nuttx/libc/libgen \
NuttX/nuttx/libc/fixedmath \
NuttX/nuttx/libc/dirent \
NuttX/nuttx/libc/bin \
NuttX/nuttx/graphics/nxtk \
NuttX/nuttx/graphics/nxsu \
NuttX/nuttx/graphics/nxmu \
NuttX/nuttx/graphics/nxglib \
NuttX/nuttx/graphics/nxglib/lcd \
NuttX/nuttx/graphics/nxglib/fb \
NuttX/nuttx/graphics/nxfonts \
NuttX/nuttx/graphics/nxconsole \
NuttX/nuttx/graphics/nxbe \
NuttX/nuttx/fs/smartfs \
NuttX/nuttx/fs/romfs \
NuttX/nuttx/fs/nxffs \
NuttX/nuttx/fs/nfs \
NuttX/nuttx/fs/mmap \
NuttX/nuttx/fs \
NuttX/nuttx/fs/fat \
NuttX/nuttx/fs/binfs \
NuttX/nuttx/drivers/wireless \
NuttX/nuttx/drivers \
NuttX/nuttx/drivers/usbhost \
NuttX/nuttx/drivers/usbdev \
NuttX/nuttx/drivers/syslog \
NuttX/nuttx/drivers/serial \
NuttX/nuttx/drivers/sercomm \
NuttX/nuttx/drivers/sensors \
NuttX/nuttx/drivers/power \
NuttX/nuttx/drivers/pipes \
NuttX/nuttx/drivers/net \
NuttX/nuttx/drivers/mtd \
NuttX/nuttx/drivers/mmcsd \
NuttX/nuttx/drivers/lcd \
NuttX/nuttx/drivers/input \
NuttX/nuttx/drivers/bch \
NuttX/nuttx/drivers/audio \
NuttX/nuttx/drivers/analog \
NuttX/nuttx/configs/zp214xpa/src \
NuttX/nuttx/configs/zkit-arm-1769/src \
NuttX/nuttx/configs/z8f64200100kit/src \
NuttX/nuttx/configs/z8encore000zco/src \
NuttX/nuttx/configs/z80sim/src \
NuttX/nuttx/configs/z16f2800100zcog/src \
NuttX/nuttx/configs/xtrs/src \
NuttX/nuttx/configs/vsn/src \
NuttX/nuttx/configs/us7032evb1/src \
NuttX/nuttx/configs/us7032evb1/shterm \
NuttX/nuttx/configs/ubw32/src \
NuttX/nuttx/configs/twr-k60n512/src \
NuttX/nuttx/configs/teensy/src \
NuttX/nuttx/configs/sure-pic32mx/src \
NuttX/nuttx/configs/stm32ldiscovery/src \
NuttX/nuttx/configs/stm32f4discovery/src \
NuttX/nuttx/configs/stm32f4discovery/kernel \
NuttX/nuttx/configs/stm32f3discovery/src \
NuttX/nuttx/configs/stm32f100rc_generic/src \
NuttX/nuttx/configs/stm32_tiny/src \
NuttX/nuttx/configs/stm3240g-eval/src \
NuttX/nuttx/configs/stm3220g-eval/src \
NuttX/nuttx/configs/stm3210e-eval/src \
NuttX/nuttx/configs/stm3210e-eval/RIDE \
NuttX/nuttx/configs/skp16c26/src \
NuttX/nuttx/configs/sim/src \
NuttX/nuttx/configs/shenzhou/src \
NuttX/nuttx/configs/sam4s-xplained/src \
NuttX/nuttx/configs/sam4l-xplained/src \
NuttX/nuttx/configs/sam3u-ek/src \
NuttX/nuttx/configs/sam3u-ek/kernel \
NuttX/nuttx/configs/qemu-i486/src \
NuttX/nuttx/configs/pjrc-8051/src \
NuttX/nuttx/configs/pirelli_dpl10/src \
NuttX/nuttx/configs/pic32mx7mmb/src \
NuttX/nuttx/configs/pic32-starterkit/src \
NuttX/nuttx/configs/pcblogic-pic32mx/src \
NuttX/nuttx/configs/open1788/src \
NuttX/nuttx/configs/open1788/kernel \
NuttX/nuttx/configs/olimex-strp711/src \
NuttX/nuttx/configs/olimex-stm32-p107/src \
NuttX/nuttx/configs/olimex-lpc2378/src \
NuttX/nuttx/configs/olimex-lpc1766stk/src \
NuttX/nuttx/configs/nutiny-nuc120/src \
NuttX/nuttx/configs/nucleus2g/src \
NuttX/nuttx/configs/ntosd-dm320/src \
NuttX/nuttx/configs/ne64badge/src \
NuttX/nuttx/configs/mx1ads/src \
NuttX/nuttx/configs/mirtoo/src \
NuttX/nuttx/configs/mikroe-stm32f4/src \
NuttX/nuttx/configs/mikroe-stm32f4/kernel \
NuttX/nuttx/configs/micropendous3/src \
NuttX/nuttx/configs/mcu123-lpc214x/src \
NuttX/nuttx/configs/mbed/src \
NuttX/nuttx/configs/lpcxpresso-lpc1768/src \
NuttX/nuttx/configs/lpc4330-xplorer/src \
NuttX/nuttx/configs/lm4f120-launchpad/src \
NuttX/nuttx/configs/lm3s8962-ek/src \
NuttX/nuttx/configs/lm3s6965-ek/src \
NuttX/nuttx/configs/lm3s6432-s2e/src \
NuttX/nuttx/configs/lincoln60/src \
NuttX/nuttx/configs/kwikstik-k40/src \
NuttX/nuttx/configs/hymini-stm32v/src \
NuttX/nuttx/configs/freedom-kl25z/src \
NuttX/nuttx/configs/fire-stm32v2/src \
NuttX/nuttx/configs/ez80f910200zco/src \
NuttX/nuttx/configs/ez80f910200kitg/src \
NuttX/nuttx/configs/ekk-lm3s9b96/src \
NuttX/nuttx/configs/eagle100/src \
NuttX/nuttx/configs/ea3152/tools \
NuttX/nuttx/configs/ea3152/src \
NuttX/nuttx/configs/ea3131/tools \
NuttX/nuttx/configs/ea3131/src \
NuttX/nuttx/configs/demo9s12ne64/src \
NuttX/nuttx/configs/compal_e99/src \
NuttX/nuttx/configs/compal_e88/src \
NuttX/nuttx/configs/cloudctrl/src \
NuttX/nuttx/configs/c5471evm/src \
NuttX/nuttx/configs/avr32dev1/src \
NuttX/nuttx/configs/amber/src \
NuttX/nuttx/binfmt \
NuttX/nuttx/binfmt/libnxflat \
NuttX/nuttx/binfmt/libelf \
NuttX/nuttx/binfmt/libbuiltin \
NuttX/nuttx/audio \
NuttX/nuttx/arch/z80/src/z80 \
NuttX/nuttx/arch/z80/src/z8 \
NuttX/nuttx/arch/z80/src/z180 \
NuttX/nuttx/arch/z80/src/ez80 \
NuttX/nuttx/arch/z80/src/common \
NuttX/nuttx/arch/z16/src/z16f \
NuttX/nuttx/arch/z16/src/common \
NuttX/nuttx/arch/x86/src/qemu \
NuttX/nuttx/arch/x86/src/i486 \
NuttX/nuttx/arch/x86/src/common \
NuttX/nuttx/arch/sim/src \
NuttX/nuttx/arch/sh/src/sh1 \
NuttX/nuttx/arch/sh/src/m16c \
NuttX/nuttx/arch/sh/src/common \
NuttX/nuttx/arch/rgmp/src/x86 \
NuttX/nuttx/arch/rgmp/src \
NuttX/nuttx/arch/rgmp/src/arm \
NuttX/nuttx/arch/mips/src/pic32mx \
NuttX/nuttx/arch/mips/src/mips32 \
NuttX/nuttx/arch/mips/src/common \
NuttX/nuttx/arch/hc/src/m9s12 \
NuttX/nuttx/arch/hc/src/common \
NuttX/nuttx/arch/avr/src/common \
NuttX/nuttx/arch/avr/src/avr32 \
NuttX/nuttx/arch/avr/src/avr \
NuttX/nuttx/arch/avr/src/atmega \
NuttX/nuttx/arch/avr/src/at90usb \
NuttX/nuttx/arch/avr/src/at32uc3 \
NuttX/nuttx/arch/arm/src \
NuttX/nuttx/arch/arm/src/str71x \
NuttX/nuttx/arch/arm/src/stm32 \
NuttX/nuttx/arch/arm/src/sam34 \
NuttX/nuttx/arch/arm/src/nuc1xx \
NuttX/nuttx/arch/arm/src/lpc43xx \
NuttX/nuttx/arch/arm/src/lpc31xx \
NuttX/nuttx/arch/arm/src/lpc2378 \
NuttX/nuttx/arch/arm/src/lpc214x \
NuttX/nuttx/arch/arm/src/lpc17xx \
NuttX/nuttx/arch/arm/src/lm \
NuttX/nuttx/arch/arm/src/kl \
NuttX/nuttx/arch/arm/src/kinetis \
NuttX/nuttx/arch/arm/src/imx \
NuttX/nuttx/arch/arm/src/dm320 \
NuttX/nuttx/arch/arm/src/common \
NuttX/nuttx/arch/arm/src/chip \
NuttX/nuttx/arch/arm/src/calypso \
NuttX/nuttx/arch/arm/src/c5471 \
NuttX/nuttx/arch/arm/src/board \
NuttX/nuttx/arch/arm/src/armv7-m \
NuttX/nuttx/arch/arm/src/armv6-m \
NuttX/nuttx/arch/arm/src/arm \
NuttX/nuttx/arch/8051/src \
NuttX/misc/uClibc++/libxx/uClibc++ \
NuttX/misc/tools/osmocon \
NuttX/misc/tools/kconfig-frontends/utils \
NuttX/misc/tools/kconfig-frontends/libs/parser \
NuttX/misc/tools/kconfig-frontends/libs/lxdialog \
NuttX/misc/tools/kconfig-frontends/frontends/qconf \
NuttX/misc/tools/kconfig-frontends/frontends/nconf \
NuttX/misc/tools/kconfig-frontends/frontends/mconf \
NuttX/misc/tools/kconfig-frontends/frontends/gconf \
NuttX/misc/tools/kconfig-frontends/frontends/conf \
NuttX/misc/sims/z80sim/src \
NuttX/misc/sims/z80sim/example \
NuttX/misc/pascal/plink \
NuttX/misc/pascal/pascal \
NuttX/misc/pascal/libpoff \
NuttX/misc/pascal/libpas \
NuttX/misc/pascal/insn32/regm \
NuttX/misc/pascal/insn32/popt \
NuttX/misc/pascal/insn32/plist \
NuttX/misc/pascal/insn32/libinsn \
NuttX/misc/pascal/insn16/prun \
NuttX/misc/pascal/insn16/popt \
NuttX/misc/pascal/insn16/plist \
NuttX/misc/pascal/insn16/libinsn \
NuttX/misc/drivers/rtl8187x \
NuttX/misc/buildroot/toolchain/sstrip \
NuttX/misc/buildroot/toolchain/nxflat/thumb2 \
NuttX/misc/buildroot/toolchain/nxflat \
NuttX/misc/buildroot/toolchain/nxflat/arm \
NuttX/misc/buildroot/package/config \
NuttX/misc/buildroot/package/config/lxdialog \
NuttX/apps/system/usbmonitor \
NuttX/apps/system/sysinfo \
NuttX/apps/system/sdcard \
NuttX/apps/system/readline \
NuttX/apps/system/ramtron \
NuttX/apps/system/ramtest \
NuttX/apps/system/poweroff \
NuttX/apps/system/install \
NuttX/apps/system/i2c \
NuttX/apps/system/free \
NuttX/apps/system/flash_eraseall \
NuttX/apps/nshlib \
NuttX/apps/netutils/xmlrpc \
NuttX/apps/netutils/webserver \
NuttX/apps/netutils/webclient \
NuttX/apps/netutils/uiplib \
NuttX/apps/netutils/thttpd \
NuttX/apps/netutils/thttpd/cgi-src \
NuttX/apps/netutils/tftpc \
NuttX/apps/netutils/telnetd \
NuttX/apps/netutils/smtp \
NuttX/apps/netutils/resolv \
NuttX/apps/netutils/json \
NuttX/apps/netutils/ftpd \
NuttX/apps/netutils/ftpc \
NuttX/apps/netutils/discover \
NuttX/apps/netutils/dhcpd \
NuttX/apps/netutils/dhcpc \
NuttX/apps/netutils/codecs \
NuttX/apps/modbus/tcp \
NuttX/apps/modbus/rtu \
NuttX/apps/modbus/nuttx \
NuttX/apps/modbus \
NuttX/apps/modbus/functions \
NuttX/apps/modbus/ascii \
NuttX/apps/interpreters/ficl/src \
NuttX/apps/graphics/tiff \
NuttX/apps/graphics/screenshot \
NuttX/apps/examples/xmlrpc \
NuttX/apps/examples/wgetjson \
NuttX/apps/examples/wget \
NuttX/apps/examples/watchdog \
NuttX/apps/examples/usbterm \
NuttX/apps/examples/usbstorage \
NuttX/apps/examples/usbserial \
NuttX/apps/examples/uip \
NuttX/apps/examples/udp \
NuttX/apps/examples/touchscreen \
NuttX/apps/examples/tiff \
NuttX/apps/examples/thttpd \
NuttX/apps/examples/thttpd/content/tasks \
NuttX/apps/examples/thttpd/content/netstat \
NuttX/apps/examples/thttpd/content/hello \
NuttX/apps/examples/telnetd \
NuttX/apps/examples/tcpecho \
NuttX/apps/examples/smart_test \
NuttX/apps/examples/smart \
NuttX/apps/examples/slcd \
NuttX/apps/examples/serloop \
NuttX/apps/examples/sendmail \
NuttX/apps/examples/romfs \
NuttX/apps/examples/rgmp \
NuttX/apps/examples/relays \
NuttX/apps/examples/qencoder \
NuttX/apps/examples/pwm \
NuttX/apps/examples/posix_spawn \
NuttX/apps/examples/posix_spawn/filesystem/redirect \
NuttX/apps/examples/posix_spawn/filesystem/hello \
NuttX/apps/examples/poll \
NuttX/apps/examples/pipe \
NuttX/apps/examples/pashello \
NuttX/apps/examples/ostest \
NuttX/apps/examples/nxtext \
NuttX/apps/examples/nxlines \
NuttX/apps/examples/nximage \
NuttX/apps/examples/nxhello \
NuttX/apps/examples/nxflat/tests/task \
NuttX/apps/examples/nxflat/tests/struct \
NuttX/apps/examples/nxflat/tests/signal \
NuttX/apps/examples/nxflat/tests/pthread \
NuttX/apps/examples/nxflat/tests/mutex \
NuttX/apps/examples/nxflat/tests/longjmp \
NuttX/apps/examples/nxflat/tests/hello++ \
NuttX/apps/examples/nxflat/tests/hello \
NuttX/apps/examples/nxflat/tests/errno \
NuttX/apps/examples/nxflat \
NuttX/apps/examples/nxffs \
NuttX/apps/examples/nxconsole \
NuttX/apps/examples/nx \
NuttX/apps/examples/null \
NuttX/apps/examples/nsh \
NuttX/apps/examples/nrf24l01_term \
NuttX/apps/examples/nettest \
NuttX/apps/examples/mtdpart \
NuttX/apps/examples/mount \
NuttX/apps/examples/modbus \
NuttX/apps/examples/mm \
NuttX/apps/examples/lcdrw \
NuttX/apps/examples/keypadtest \
NuttX/apps/examples/json \
NuttX/apps/examples/igmp \
NuttX/apps/examples/hidkbd \
NuttX/apps/examples/helloxx \
NuttX/apps/examples/hello \
NuttX/apps/examples/ftpd \
NuttX/apps/examples/ftpc \
NuttX/apps/examples/flash_test \
NuttX/apps/examples/elf/tests/task \
NuttX/apps/examples/elf/tests/struct \
NuttX/apps/examples/elf/tests/signal \
NuttX/apps/examples/elf/tests/pthread \
NuttX/apps/examples/elf/tests/mutex \
NuttX/apps/examples/elf/tests/longjmp \
NuttX/apps/examples/elf/tests/helloxx \
NuttX/apps/examples/elf/tests/hello \
NuttX/apps/examples/elf/tests/errno \
NuttX/apps/examples/elf \
NuttX/apps/examples/discover \
NuttX/apps/examples/dhcpd \
NuttX/apps/examples/cxxtest \
NuttX/apps/examples/composite \
NuttX/apps/examples/cdcacm \
NuttX/apps/examples/can \
NuttX/apps/examples/buttons \
NuttX/apps/examples/adc \
NuttX/apps/builtin \
NuttX/NxWidgets/nxwm/src \
NuttX/NxWidgets/libnxwidgets/src \
NuttX/NxWidgets/UnitTests/nxwm \
NuttX/NxWidgets/UnitTests/CTextBox \
NuttX/NxWidgets/UnitTests/CSliderVertical \
NuttX/NxWidgets/UnitTests/CSliderHorizonal \
NuttX/NxWidgets/UnitTests/CScrollbarVertical \
NuttX/NxWidgets/UnitTests/CScrollbarHorizontal \
NuttX/NxWidgets/UnitTests/CRadioButton \
NuttX/NxWidgets/UnitTests/CProgressBar \
NuttX/NxWidgets/UnitTests/CListBox \
NuttX/NxWidgets/UnitTests/CLatchButtonArray \
NuttX/NxWidgets/UnitTests/CLatchButton \
NuttX/NxWidgets/UnitTests/CLabel \
NuttX/NxWidgets/UnitTests/CKeypad \
NuttX/NxWidgets/UnitTests/CImage \
NuttX/NxWidgets/UnitTests/CGlyphSliderHorizontal \
NuttX/NxWidgets/UnitTests/CGlyphButton \
NuttX/NxWidgets/UnitTests/CCheckBox \
NuttX/NxWidgets/UnitTests/CButtonArray \
NuttX/NxWidgets/UnitTests/CButton \
Build/px4io-v2_default.build/f/Firmware/src/modules/systemlib \
Build/px4io-v2_default.build/f/Firmware/src/modules/systemlib/pwm_limit \
Build/px4io-v2_default.build/f/Firmware/src/modules/systemlib/mixer \
Build/px4io-v2_default.build/f/Firmware/src/modules/px4iofirmware \
Build/px4io-v2_default.build/f/Firmware/src/lib/rc \
Build/px4io-v2_default.build/f/Firmware/src/drivers/stm32 \
Build/px4io-v2_default.build/f/Firmware/src/drivers/boards/px4io-v2 \
Build/px4io-v2_default.build/f/Firmware/Build/px4io-v2_default.build \
Build/px4io-v2_default.build \
Build/px4fmu-v2_sailing.build \
Build/px4fmu-v2_sailing.build/f/Firmware/src/systemcmds/ver \
Build/px4fmu-v2_sailing.build/f/Firmware/src/systemcmds/top \
Build/px4fmu-v2_sailing.build/f/Firmware/src/systemcmds/tests \
Build/px4fmu-v2_sailing.build/f/Firmware/src/systemcmds/reboot \
Build/px4fmu-v2_sailing.build/f/Firmware/src/systemcmds/pwm \
Build/px4fmu-v2_sailing.build/f/Firmware/src/systemcmds/preflight_check \
Build/px4fmu-v2_sailing.build/f/Firmware/src/systemcmds/perf \
Build/px4fmu-v2_sailing.build/f/Firmware/src/systemcmds/param \
Build/px4fmu-v2_sailing.build/f/Firmware/src/systemcmds/nshterm \
Build/px4fmu-v2_sailing.build/f/Firmware/src/systemcmds/mtd \
Build/px4fmu-v2_sailing.build/f/Firmware/src/systemcmds/mixer \
Build/px4fmu-v2_sailing.build/f/Firmware/src/systemcmds/esc_calib \
Build/px4fmu-v2_sailing.build/f/Firmware/src/systemcmds/dumpfile \
Build/px4fmu-v2_sailing.build/f/Firmware/src/systemcmds/config \
Build/px4fmu-v2_sailing.build/f/Firmware/src/systemcmds/boardinfo \
Build/px4fmu-v2_sailing.build/f/Firmware/src/systemcmds/bl_update \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/uavcan \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/uavcan/sensors \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/uavcan/actuators \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/uORB \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/systemlib \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/systemlib/pwm_limit \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/systemlib/pid \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/systemlib/param \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/systemlib/mixer \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/systemlib/bson \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/sensors \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/sdlog2 \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/path_planning \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/path_planning/parser_sensorboard \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/path_planning/mission \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/path_planning/kalman_tracker \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/parser_200WX \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/navigator \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/mavlink \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/gpio_led \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/ekf_att_pos_estimator \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/dataman \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/controllib/uorb \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/controllib \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/controllib/block \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/commander \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/autonomous_sailing \
Build/px4fmu-v2_sailing.build/f/Firmware/src/modules/autonomous_sailing/mpcForces \
Build/px4fmu-v2_sailing.build/f/Firmware/src/lib/mathlib \
Build/px4fmu-v2_sailing.build/f/Firmware/src/lib/mathlib/math/test \
Build/px4fmu-v2_sailing.build/f/Firmware/src/lib/mathlib/math/filter \
Build/px4fmu-v2_sailing.build/f/Firmware/src/lib/mathlib/math \
Build/px4fmu-v2_sailing.build/f/Firmware/src/lib/launchdetection \
Build/px4fmu-v2_sailing.build/f/Firmware/src/lib/geo_lookup \
Build/px4fmu-v2_sailing.build/f/Firmware/src/lib/geo \
Build/px4fmu-v2_sailing.build/f/Firmware/src/lib/external_lgpl/tecs \
Build/px4fmu-v2_sailing.build/f/Firmware/src/lib/external_lgpl \
Build/px4fmu-v2_sailing.build/f/Firmware/src/lib/ecl \
Build/px4fmu-v2_sailing.build/f/Firmware/src/lib/ecl/l1 \
Build/px4fmu-v2_sailing.build/f/Firmware/src/lib/ecl/attitude_fw \
Build/px4fmu-v2_sailing.build/f/Firmware/src/lib/conversion \
Build/px4fmu-v2_sailing.build/f/Firmware/src/drivers/stm32/tone_alarm \
Build/px4fmu-v2_sailing.build/f/Firmware/src/drivers/stm32 \
Build/px4fmu-v2_sailing.build/f/Firmware/src/drivers/stm32/adc \
Build/px4fmu-v2_sailing.build/f/Firmware/src/drivers/sf0x \
Build/px4fmu-v2_sailing.build/f/Firmware/src/drivers/rgbled \
Build/px4fmu-v2_sailing.build/f/Firmware/src/drivers/px4io \
Build/px4fmu-v2_sailing.build/f/Firmware/src/drivers/px4fmu \
Build/px4fmu-v2_sailing.build/f/Firmware/src/drivers/px4flow \
Build/px4fmu-v2_sailing.build/f/Firmware/src/drivers/pca8574 \
Build/px4fmu-v2_sailing.build/f/Firmware/src/drivers/ms5611 \
Build/px4fmu-v2_sailing.build/f/Firmware/src/drivers/mpu6000 \
Build/px4fmu-v2_sailing.build/f/Firmware/src/drivers/mkblctrl \
Build/px4fmu-v2_sailing.build/f/Firmware/src/drivers/mb12xx \
Build/px4fmu-v2_sailing.build/f/Firmware/src/drivers/lsm303d \
Build/px4fmu-v2_sailing.build/f/Firmware/src/drivers/ll40ls \
Build/px4fmu-v2_sailing.build/f/Firmware/src/drivers/led \
Build/px4fmu-v2_sailing.build/f/Firmware/src/drivers/l3gd20 \
Build/px4fmu-v2_sailing.build/f/Firmware/src/drivers/hott \
Build/px4fmu-v2_sailing.build/f/Firmware/src/drivers/hott/hott_telemetry \
Build/px4fmu-v2_sailing.build/f/Firmware/src/drivers/hott/hott_sensors \
Build/px4fmu-v2_sailing.build/f/Firmware/src/drivers/hmc5883 \
Build/px4fmu-v2_sailing.build/f/Firmware/src/drivers/gps \
Build/px4fmu-v2_sailing.build/f/Firmware/src/drivers/frsky_telemetry \
Build/px4fmu-v2_sailing.build/f/Firmware/src/drivers/device \
Build/px4fmu-v2_sailing.build/f/Firmware/src/drivers/boards/px4fmu-v2 \
Build/px4fmu-v2_sailing.build/f/Firmware/src/drivers/blinkm \
Build/px4fmu-v2_sailing.build/f/Firmware/Build/px4fmu-v2_sailing.build \

