################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../NuttX/nuttx/sched/atexit.c \
../NuttX/nuttx/sched/clock_abstime2ticks.c \
../NuttX/nuttx/sched/clock_dow.c \
../NuttX/nuttx/sched/clock_getres.c \
../NuttX/nuttx/sched/clock_gettime.c \
../NuttX/nuttx/sched/clock_gettimeofday.c \
../NuttX/nuttx/sched/clock_initialize.c \
../NuttX/nuttx/sched/clock_settime.c \
../NuttX/nuttx/sched/clock_systimer.c \
../NuttX/nuttx/sched/clock_ticks2time.c \
../NuttX/nuttx/sched/clock_time2ticks.c \
../NuttX/nuttx/sched/env_clearenv.c \
../NuttX/nuttx/sched/env_dup.c \
../NuttX/nuttx/sched/env_findvar.c \
../NuttX/nuttx/sched/env_getenv.c \
../NuttX/nuttx/sched/env_getenvironptr.c \
../NuttX/nuttx/sched/env_putenv.c \
../NuttX/nuttx/sched/env_release.c \
../NuttX/nuttx/sched/env_removevar.c \
../NuttX/nuttx/sched/env_setenv.c \
../NuttX/nuttx/sched/env_unsetenv.c \
../NuttX/nuttx/sched/errno_get.c \
../NuttX/nuttx/sched/errno_getptr.c \
../NuttX/nuttx/sched/errno_set.c \
../NuttX/nuttx/sched/exit.c \
../NuttX/nuttx/sched/getpid.c \
../NuttX/nuttx/sched/group_childstatus.c \
../NuttX/nuttx/sched/group_create.c \
../NuttX/nuttx/sched/group_find.c \
../NuttX/nuttx/sched/group_foreachchild.c \
../NuttX/nuttx/sched/group_join.c \
../NuttX/nuttx/sched/group_killchildren.c \
../NuttX/nuttx/sched/group_leave.c \
../NuttX/nuttx/sched/group_setupidlefiles.c \
../NuttX/nuttx/sched/group_setupstreams.c \
../NuttX/nuttx/sched/group_setuptaskfiles.c \
../NuttX/nuttx/sched/group_signal.c \
../NuttX/nuttx/sched/irq_attach.c \
../NuttX/nuttx/sched/irq_dispatch.c \
../NuttX/nuttx/sched/irq_initialize.c \
../NuttX/nuttx/sched/irq_unexpectedisr.c \
../NuttX/nuttx/sched/mq_close.c \
../NuttX/nuttx/sched/mq_descreate.c \
../NuttX/nuttx/sched/mq_findnamed.c \
../NuttX/nuttx/sched/mq_initialize.c \
../NuttX/nuttx/sched/mq_msgfree.c \
../NuttX/nuttx/sched/mq_msgqfree.c \
../NuttX/nuttx/sched/mq_notify.c \
../NuttX/nuttx/sched/mq_open.c \
../NuttX/nuttx/sched/mq_rcvinternal.c \
../NuttX/nuttx/sched/mq_receive.c \
../NuttX/nuttx/sched/mq_recover.c \
../NuttX/nuttx/sched/mq_release.c \
../NuttX/nuttx/sched/mq_send.c \
../NuttX/nuttx/sched/mq_sndinternal.c \
../NuttX/nuttx/sched/mq_timedreceive.c \
../NuttX/nuttx/sched/mq_timedsend.c \
../NuttX/nuttx/sched/mq_unlink.c \
../NuttX/nuttx/sched/mq_waitirq.c \
../NuttX/nuttx/sched/on_exit.c \
../NuttX/nuttx/sched/os_bringup.c \
../NuttX/nuttx/sched/os_start.c \
../NuttX/nuttx/sched/pause.c \
../NuttX/nuttx/sched/pg_miss.c \
../NuttX/nuttx/sched/pg_worker.c \
../NuttX/nuttx/sched/prctl.c \
../NuttX/nuttx/sched/pthread_barrierdestroy.c \
../NuttX/nuttx/sched/pthread_barrierinit.c \
../NuttX/nuttx/sched/pthread_barrierwait.c \
../NuttX/nuttx/sched/pthread_cancel.c \
../NuttX/nuttx/sched/pthread_completejoin.c \
../NuttX/nuttx/sched/pthread_condbroadcast.c \
../NuttX/nuttx/sched/pthread_conddestroy.c \
../NuttX/nuttx/sched/pthread_condinit.c \
../NuttX/nuttx/sched/pthread_condsignal.c \
../NuttX/nuttx/sched/pthread_condtimedwait.c \
../NuttX/nuttx/sched/pthread_condwait.c \
../NuttX/nuttx/sched/pthread_create.c \
../NuttX/nuttx/sched/pthread_detach.c \
../NuttX/nuttx/sched/pthread_exit.c \
../NuttX/nuttx/sched/pthread_findjoininfo.c \
../NuttX/nuttx/sched/pthread_getschedparam.c \
../NuttX/nuttx/sched/pthread_getspecific.c \
../NuttX/nuttx/sched/pthread_initialize.c \
../NuttX/nuttx/sched/pthread_join.c \
../NuttX/nuttx/sched/pthread_keycreate.c \
../NuttX/nuttx/sched/pthread_keydelete.c \
../NuttX/nuttx/sched/pthread_kill.c \
../NuttX/nuttx/sched/pthread_mutexdestroy.c \
../NuttX/nuttx/sched/pthread_mutexinit.c \
../NuttX/nuttx/sched/pthread_mutexlock.c \
../NuttX/nuttx/sched/pthread_mutextrylock.c \
../NuttX/nuttx/sched/pthread_mutexunlock.c \
../NuttX/nuttx/sched/pthread_once.c \
../NuttX/nuttx/sched/pthread_release.c \
../NuttX/nuttx/sched/pthread_setcancelstate.c \
../NuttX/nuttx/sched/pthread_setschedparam.c \
../NuttX/nuttx/sched/pthread_setschedprio.c \
../NuttX/nuttx/sched/pthread_setspecific.c \
../NuttX/nuttx/sched/pthread_sigmask.c \
../NuttX/nuttx/sched/pthread_yield.c \
../NuttX/nuttx/sched/sched_addblocked.c \
../NuttX/nuttx/sched/sched_addprioritized.c \
../NuttX/nuttx/sched/sched_addreadytorun.c \
../NuttX/nuttx/sched/sched_foreach.c \
../NuttX/nuttx/sched/sched_free.c \
../NuttX/nuttx/sched/sched_garbage.c \
../NuttX/nuttx/sched/sched_getfiles.c \
../NuttX/nuttx/sched/sched_getparam.c \
../NuttX/nuttx/sched/sched_getscheduler.c \
../NuttX/nuttx/sched/sched_getsockets.c \
../NuttX/nuttx/sched/sched_getstreams.c \
../NuttX/nuttx/sched/sched_gettcb.c \
../NuttX/nuttx/sched/sched_lock.c \
../NuttX/nuttx/sched/sched_lockcount.c \
../NuttX/nuttx/sched/sched_mergepending.c \
../NuttX/nuttx/sched/sched_processtimer.c \
../NuttX/nuttx/sched/sched_releasetcb.c \
../NuttX/nuttx/sched/sched_removeblocked.c \
../NuttX/nuttx/sched/sched_removereadytorun.c \
../NuttX/nuttx/sched/sched_reprioritize.c \
../NuttX/nuttx/sched/sched_rrgetinterval.c \
../NuttX/nuttx/sched/sched_self.c \
../NuttX/nuttx/sched/sched_setparam.c \
../NuttX/nuttx/sched/sched_setpriority.c \
../NuttX/nuttx/sched/sched_setscheduler.c \
../NuttX/nuttx/sched/sched_unlock.c \
../NuttX/nuttx/sched/sched_verifytcb.c \
../NuttX/nuttx/sched/sched_wait.c \
../NuttX/nuttx/sched/sched_waitid.c \
../NuttX/nuttx/sched/sched_waitpid.c \
../NuttX/nuttx/sched/sched_yield.c \
../NuttX/nuttx/sched/sem_close.c \
../NuttX/nuttx/sched/sem_destroy.c \
../NuttX/nuttx/sched/sem_findnamed.c \
../NuttX/nuttx/sched/sem_holder.c \
../NuttX/nuttx/sched/sem_initialize.c \
../NuttX/nuttx/sched/sem_open.c \
../NuttX/nuttx/sched/sem_post.c \
../NuttX/nuttx/sched/sem_timedwait.c \
../NuttX/nuttx/sched/sem_trywait.c \
../NuttX/nuttx/sched/sem_unlink.c \
../NuttX/nuttx/sched/sem_wait.c \
../NuttX/nuttx/sched/sem_waitirq.c \
../NuttX/nuttx/sched/sig_action.c \
../NuttX/nuttx/sched/sig_allocatependingsigaction.c \
../NuttX/nuttx/sched/sig_cleanup.c \
../NuttX/nuttx/sched/sig_deliver.c \
../NuttX/nuttx/sched/sig_dispatch.c \
../NuttX/nuttx/sched/sig_findaction.c \
../NuttX/nuttx/sched/sig_initialize.c \
../NuttX/nuttx/sched/sig_kill.c \
../NuttX/nuttx/sched/sig_lowest.c \
../NuttX/nuttx/sched/sig_mqnotempty.c \
../NuttX/nuttx/sched/sig_pending.c \
../NuttX/nuttx/sched/sig_procmask.c \
../NuttX/nuttx/sched/sig_queue.c \
../NuttX/nuttx/sched/sig_releasependingsigaction.c \
../NuttX/nuttx/sched/sig_releasependingsignal.c \
../NuttX/nuttx/sched/sig_removependingsignal.c \
../NuttX/nuttx/sched/sig_suspend.c \
../NuttX/nuttx/sched/sig_timedwait.c \
../NuttX/nuttx/sched/sig_unmaskpendingsignal.c \
../NuttX/nuttx/sched/sig_waitinfo.c \
../NuttX/nuttx/sched/sleep.c \
../NuttX/nuttx/sched/task_activate.c \
../NuttX/nuttx/sched/task_create.c \
../NuttX/nuttx/sched/task_delete.c \
../NuttX/nuttx/sched/task_exit.c \
../NuttX/nuttx/sched/task_exithook.c \
../NuttX/nuttx/sched/task_getgroup.c \
../NuttX/nuttx/sched/task_init.c \
../NuttX/nuttx/sched/task_posixspawn.c \
../NuttX/nuttx/sched/task_recover.c \
../NuttX/nuttx/sched/task_reparent.c \
../NuttX/nuttx/sched/task_restart.c \
../NuttX/nuttx/sched/task_setup.c \
../NuttX/nuttx/sched/task_spawn.c \
../NuttX/nuttx/sched/task_spawnparms.c \
../NuttX/nuttx/sched/task_start.c \
../NuttX/nuttx/sched/task_starthook.c \
../NuttX/nuttx/sched/task_terminate.c \
../NuttX/nuttx/sched/task_vfork.c \
../NuttX/nuttx/sched/timer_create.c \
../NuttX/nuttx/sched/timer_delete.c \
../NuttX/nuttx/sched/timer_getoverrun.c \
../NuttX/nuttx/sched/timer_gettime.c \
../NuttX/nuttx/sched/timer_initialize.c \
../NuttX/nuttx/sched/timer_release.c \
../NuttX/nuttx/sched/timer_settime.c \
../NuttX/nuttx/sched/usleep.c \
../NuttX/nuttx/sched/wd_cancel.c \
../NuttX/nuttx/sched/wd_create.c \
../NuttX/nuttx/sched/wd_delete.c \
../NuttX/nuttx/sched/wd_gettime.c \
../NuttX/nuttx/sched/wd_initialize.c \
../NuttX/nuttx/sched/wd_start.c 

O_SRCS += \
../NuttX/nuttx/sched/clock_abstime2ticks.o \
../NuttX/nuttx/sched/clock_getres.o \
../NuttX/nuttx/sched/clock_gettime.o \
../NuttX/nuttx/sched/clock_gettimeofday.o \
../NuttX/nuttx/sched/clock_initialize.o \
../NuttX/nuttx/sched/clock_settime.o \
../NuttX/nuttx/sched/clock_systimer.o \
../NuttX/nuttx/sched/clock_ticks2time.o \
../NuttX/nuttx/sched/clock_time2ticks.o \
../NuttX/nuttx/sched/errno_get.o \
../NuttX/nuttx/sched/errno_getptr.o \
../NuttX/nuttx/sched/errno_set.o \
../NuttX/nuttx/sched/exit.o \
../NuttX/nuttx/sched/getpid.o \
../NuttX/nuttx/sched/group_create.o \
../NuttX/nuttx/sched/group_find.o \
../NuttX/nuttx/sched/group_foreachchild.o \
../NuttX/nuttx/sched/group_join.o \
../NuttX/nuttx/sched/group_killchildren.o \
../NuttX/nuttx/sched/group_leave.o \
../NuttX/nuttx/sched/group_setupidlefiles.o \
../NuttX/nuttx/sched/group_setupstreams.o \
../NuttX/nuttx/sched/group_setuptaskfiles.o \
../NuttX/nuttx/sched/irq_attach.o \
../NuttX/nuttx/sched/irq_dispatch.o \
../NuttX/nuttx/sched/irq_initialize.o \
../NuttX/nuttx/sched/irq_unexpectedisr.o \
../NuttX/nuttx/sched/os_bringup.o \
../NuttX/nuttx/sched/os_start.o \
../NuttX/nuttx/sched/prctl.o \
../NuttX/nuttx/sched/sched_addblocked.o \
../NuttX/nuttx/sched/sched_addprioritized.o \
../NuttX/nuttx/sched/sched_addreadytorun.o \
../NuttX/nuttx/sched/sched_foreach.o \
../NuttX/nuttx/sched/sched_free.o \
../NuttX/nuttx/sched/sched_garbage.o \
../NuttX/nuttx/sched/sched_getfiles.o \
../NuttX/nuttx/sched/sched_getparam.o \
../NuttX/nuttx/sched/sched_getscheduler.o \
../NuttX/nuttx/sched/sched_getsockets.o \
../NuttX/nuttx/sched/sched_getstreams.o \
../NuttX/nuttx/sched/sched_gettcb.o \
../NuttX/nuttx/sched/sched_lock.o \
../NuttX/nuttx/sched/sched_lockcount.o \
../NuttX/nuttx/sched/sched_mergepending.o \
../NuttX/nuttx/sched/sched_processtimer.o \
../NuttX/nuttx/sched/sched_releasetcb.o \
../NuttX/nuttx/sched/sched_removeblocked.o \
../NuttX/nuttx/sched/sched_removereadytorun.o \
../NuttX/nuttx/sched/sched_rrgetinterval.o \
../NuttX/nuttx/sched/sched_self.o \
../NuttX/nuttx/sched/sched_setparam.o \
../NuttX/nuttx/sched/sched_setpriority.o \
../NuttX/nuttx/sched/sched_setscheduler.o \
../NuttX/nuttx/sched/sched_unlock.o \
../NuttX/nuttx/sched/sched_verifytcb.o \
../NuttX/nuttx/sched/sched_yield.o \
../NuttX/nuttx/sched/sem_close.o \
../NuttX/nuttx/sched/sem_destroy.o \
../NuttX/nuttx/sched/sem_findnamed.o \
../NuttX/nuttx/sched/sem_initialize.o \
../NuttX/nuttx/sched/sem_open.o \
../NuttX/nuttx/sched/sem_post.o \
../NuttX/nuttx/sched/sem_timedwait.o \
../NuttX/nuttx/sched/sem_trywait.o \
../NuttX/nuttx/sched/sem_unlink.o \
../NuttX/nuttx/sched/sem_wait.o \
../NuttX/nuttx/sched/task_activate.o \
../NuttX/nuttx/sched/task_create.o \
../NuttX/nuttx/sched/task_delete.o \
../NuttX/nuttx/sched/task_exit.o \
../NuttX/nuttx/sched/task_exithook.o \
../NuttX/nuttx/sched/task_getgroup.o \
../NuttX/nuttx/sched/task_init.o \
../NuttX/nuttx/sched/task_recover.o \
../NuttX/nuttx/sched/task_restart.o \
../NuttX/nuttx/sched/task_setup.o \
../NuttX/nuttx/sched/task_spawn.o \
../NuttX/nuttx/sched/task_spawnparms.o \
../NuttX/nuttx/sched/task_start.o \
../NuttX/nuttx/sched/task_terminate.o \
../NuttX/nuttx/sched/wd_cancel.o \
../NuttX/nuttx/sched/wd_create.o \
../NuttX/nuttx/sched/wd_delete.o \
../NuttX/nuttx/sched/wd_gettime.o \
../NuttX/nuttx/sched/wd_initialize.o \
../NuttX/nuttx/sched/wd_start.o 

OBJS += \
./NuttX/nuttx/sched/atexit.o \
./NuttX/nuttx/sched/clock_abstime2ticks.o \
./NuttX/nuttx/sched/clock_dow.o \
./NuttX/nuttx/sched/clock_getres.o \
./NuttX/nuttx/sched/clock_gettime.o \
./NuttX/nuttx/sched/clock_gettimeofday.o \
./NuttX/nuttx/sched/clock_initialize.o \
./NuttX/nuttx/sched/clock_settime.o \
./NuttX/nuttx/sched/clock_systimer.o \
./NuttX/nuttx/sched/clock_ticks2time.o \
./NuttX/nuttx/sched/clock_time2ticks.o \
./NuttX/nuttx/sched/env_clearenv.o \
./NuttX/nuttx/sched/env_dup.o \
./NuttX/nuttx/sched/env_findvar.o \
./NuttX/nuttx/sched/env_getenv.o \
./NuttX/nuttx/sched/env_getenvironptr.o \
./NuttX/nuttx/sched/env_putenv.o \
./NuttX/nuttx/sched/env_release.o \
./NuttX/nuttx/sched/env_removevar.o \
./NuttX/nuttx/sched/env_setenv.o \
./NuttX/nuttx/sched/env_unsetenv.o \
./NuttX/nuttx/sched/errno_get.o \
./NuttX/nuttx/sched/errno_getptr.o \
./NuttX/nuttx/sched/errno_set.o \
./NuttX/nuttx/sched/exit.o \
./NuttX/nuttx/sched/getpid.o \
./NuttX/nuttx/sched/group_childstatus.o \
./NuttX/nuttx/sched/group_create.o \
./NuttX/nuttx/sched/group_find.o \
./NuttX/nuttx/sched/group_foreachchild.o \
./NuttX/nuttx/sched/group_join.o \
./NuttX/nuttx/sched/group_killchildren.o \
./NuttX/nuttx/sched/group_leave.o \
./NuttX/nuttx/sched/group_setupidlefiles.o \
./NuttX/nuttx/sched/group_setupstreams.o \
./NuttX/nuttx/sched/group_setuptaskfiles.o \
./NuttX/nuttx/sched/group_signal.o \
./NuttX/nuttx/sched/irq_attach.o \
./NuttX/nuttx/sched/irq_dispatch.o \
./NuttX/nuttx/sched/irq_initialize.o \
./NuttX/nuttx/sched/irq_unexpectedisr.o \
./NuttX/nuttx/sched/mq_close.o \
./NuttX/nuttx/sched/mq_descreate.o \
./NuttX/nuttx/sched/mq_findnamed.o \
./NuttX/nuttx/sched/mq_initialize.o \
./NuttX/nuttx/sched/mq_msgfree.o \
./NuttX/nuttx/sched/mq_msgqfree.o \
./NuttX/nuttx/sched/mq_notify.o \
./NuttX/nuttx/sched/mq_open.o \
./NuttX/nuttx/sched/mq_rcvinternal.o \
./NuttX/nuttx/sched/mq_receive.o \
./NuttX/nuttx/sched/mq_recover.o \
./NuttX/nuttx/sched/mq_release.o \
./NuttX/nuttx/sched/mq_send.o \
./NuttX/nuttx/sched/mq_sndinternal.o \
./NuttX/nuttx/sched/mq_timedreceive.o \
./NuttX/nuttx/sched/mq_timedsend.o \
./NuttX/nuttx/sched/mq_unlink.o \
./NuttX/nuttx/sched/mq_waitirq.o \
./NuttX/nuttx/sched/on_exit.o \
./NuttX/nuttx/sched/os_bringup.o \
./NuttX/nuttx/sched/os_start.o \
./NuttX/nuttx/sched/pause.o \
./NuttX/nuttx/sched/pg_miss.o \
./NuttX/nuttx/sched/pg_worker.o \
./NuttX/nuttx/sched/prctl.o \
./NuttX/nuttx/sched/pthread_barrierdestroy.o \
./NuttX/nuttx/sched/pthread_barrierinit.o \
./NuttX/nuttx/sched/pthread_barrierwait.o \
./NuttX/nuttx/sched/pthread_cancel.o \
./NuttX/nuttx/sched/pthread_completejoin.o \
./NuttX/nuttx/sched/pthread_condbroadcast.o \
./NuttX/nuttx/sched/pthread_conddestroy.o \
./NuttX/nuttx/sched/pthread_condinit.o \
./NuttX/nuttx/sched/pthread_condsignal.o \
./NuttX/nuttx/sched/pthread_condtimedwait.o \
./NuttX/nuttx/sched/pthread_condwait.o \
./NuttX/nuttx/sched/pthread_create.o \
./NuttX/nuttx/sched/pthread_detach.o \
./NuttX/nuttx/sched/pthread_exit.o \
./NuttX/nuttx/sched/pthread_findjoininfo.o \
./NuttX/nuttx/sched/pthread_getschedparam.o \
./NuttX/nuttx/sched/pthread_getspecific.o \
./NuttX/nuttx/sched/pthread_initialize.o \
./NuttX/nuttx/sched/pthread_join.o \
./NuttX/nuttx/sched/pthread_keycreate.o \
./NuttX/nuttx/sched/pthread_keydelete.o \
./NuttX/nuttx/sched/pthread_kill.o \
./NuttX/nuttx/sched/pthread_mutexdestroy.o \
./NuttX/nuttx/sched/pthread_mutexinit.o \
./NuttX/nuttx/sched/pthread_mutexlock.o \
./NuttX/nuttx/sched/pthread_mutextrylock.o \
./NuttX/nuttx/sched/pthread_mutexunlock.o \
./NuttX/nuttx/sched/pthread_once.o \
./NuttX/nuttx/sched/pthread_release.o \
./NuttX/nuttx/sched/pthread_setcancelstate.o \
./NuttX/nuttx/sched/pthread_setschedparam.o \
./NuttX/nuttx/sched/pthread_setschedprio.o \
./NuttX/nuttx/sched/pthread_setspecific.o \
./NuttX/nuttx/sched/pthread_sigmask.o \
./NuttX/nuttx/sched/pthread_yield.o \
./NuttX/nuttx/sched/sched_addblocked.o \
./NuttX/nuttx/sched/sched_addprioritized.o \
./NuttX/nuttx/sched/sched_addreadytorun.o \
./NuttX/nuttx/sched/sched_foreach.o \
./NuttX/nuttx/sched/sched_free.o \
./NuttX/nuttx/sched/sched_garbage.o \
./NuttX/nuttx/sched/sched_getfiles.o \
./NuttX/nuttx/sched/sched_getparam.o \
./NuttX/nuttx/sched/sched_getscheduler.o \
./NuttX/nuttx/sched/sched_getsockets.o \
./NuttX/nuttx/sched/sched_getstreams.o \
./NuttX/nuttx/sched/sched_gettcb.o \
./NuttX/nuttx/sched/sched_lock.o \
./NuttX/nuttx/sched/sched_lockcount.o \
./NuttX/nuttx/sched/sched_mergepending.o \
./NuttX/nuttx/sched/sched_processtimer.o \
./NuttX/nuttx/sched/sched_releasetcb.o \
./NuttX/nuttx/sched/sched_removeblocked.o \
./NuttX/nuttx/sched/sched_removereadytorun.o \
./NuttX/nuttx/sched/sched_reprioritize.o \
./NuttX/nuttx/sched/sched_rrgetinterval.o \
./NuttX/nuttx/sched/sched_self.o \
./NuttX/nuttx/sched/sched_setparam.o \
./NuttX/nuttx/sched/sched_setpriority.o \
./NuttX/nuttx/sched/sched_setscheduler.o \
./NuttX/nuttx/sched/sched_unlock.o \
./NuttX/nuttx/sched/sched_verifytcb.o \
./NuttX/nuttx/sched/sched_wait.o \
./NuttX/nuttx/sched/sched_waitid.o \
./NuttX/nuttx/sched/sched_waitpid.o \
./NuttX/nuttx/sched/sched_yield.o \
./NuttX/nuttx/sched/sem_close.o \
./NuttX/nuttx/sched/sem_destroy.o \
./NuttX/nuttx/sched/sem_findnamed.o \
./NuttX/nuttx/sched/sem_holder.o \
./NuttX/nuttx/sched/sem_initialize.o \
./NuttX/nuttx/sched/sem_open.o \
./NuttX/nuttx/sched/sem_post.o \
./NuttX/nuttx/sched/sem_timedwait.o \
./NuttX/nuttx/sched/sem_trywait.o \
./NuttX/nuttx/sched/sem_unlink.o \
./NuttX/nuttx/sched/sem_wait.o \
./NuttX/nuttx/sched/sem_waitirq.o \
./NuttX/nuttx/sched/sig_action.o \
./NuttX/nuttx/sched/sig_allocatependingsigaction.o \
./NuttX/nuttx/sched/sig_cleanup.o \
./NuttX/nuttx/sched/sig_deliver.o \
./NuttX/nuttx/sched/sig_dispatch.o \
./NuttX/nuttx/sched/sig_findaction.o \
./NuttX/nuttx/sched/sig_initialize.o \
./NuttX/nuttx/sched/sig_kill.o \
./NuttX/nuttx/sched/sig_lowest.o \
./NuttX/nuttx/sched/sig_mqnotempty.o \
./NuttX/nuttx/sched/sig_pending.o \
./NuttX/nuttx/sched/sig_procmask.o \
./NuttX/nuttx/sched/sig_queue.o \
./NuttX/nuttx/sched/sig_releasependingsigaction.o \
./NuttX/nuttx/sched/sig_releasependingsignal.o \
./NuttX/nuttx/sched/sig_removependingsignal.o \
./NuttX/nuttx/sched/sig_suspend.o \
./NuttX/nuttx/sched/sig_timedwait.o \
./NuttX/nuttx/sched/sig_unmaskpendingsignal.o \
./NuttX/nuttx/sched/sig_waitinfo.o \
./NuttX/nuttx/sched/sleep.o \
./NuttX/nuttx/sched/task_activate.o \
./NuttX/nuttx/sched/task_create.o \
./NuttX/nuttx/sched/task_delete.o \
./NuttX/nuttx/sched/task_exit.o \
./NuttX/nuttx/sched/task_exithook.o \
./NuttX/nuttx/sched/task_getgroup.o \
./NuttX/nuttx/sched/task_init.o \
./NuttX/nuttx/sched/task_posixspawn.o \
./NuttX/nuttx/sched/task_recover.o \
./NuttX/nuttx/sched/task_reparent.o \
./NuttX/nuttx/sched/task_restart.o \
./NuttX/nuttx/sched/task_setup.o \
./NuttX/nuttx/sched/task_spawn.o \
./NuttX/nuttx/sched/task_spawnparms.o \
./NuttX/nuttx/sched/task_start.o \
./NuttX/nuttx/sched/task_starthook.o \
./NuttX/nuttx/sched/task_terminate.o \
./NuttX/nuttx/sched/task_vfork.o \
./NuttX/nuttx/sched/timer_create.o \
./NuttX/nuttx/sched/timer_delete.o \
./NuttX/nuttx/sched/timer_getoverrun.o \
./NuttX/nuttx/sched/timer_gettime.o \
./NuttX/nuttx/sched/timer_initialize.o \
./NuttX/nuttx/sched/timer_release.o \
./NuttX/nuttx/sched/timer_settime.o \
./NuttX/nuttx/sched/usleep.o \
./NuttX/nuttx/sched/wd_cancel.o \
./NuttX/nuttx/sched/wd_create.o \
./NuttX/nuttx/sched/wd_delete.o \
./NuttX/nuttx/sched/wd_gettime.o \
./NuttX/nuttx/sched/wd_initialize.o \
./NuttX/nuttx/sched/wd_start.o 

C_DEPS += \
./NuttX/nuttx/sched/atexit.d \
./NuttX/nuttx/sched/clock_abstime2ticks.d \
./NuttX/nuttx/sched/clock_dow.d \
./NuttX/nuttx/sched/clock_getres.d \
./NuttX/nuttx/sched/clock_gettime.d \
./NuttX/nuttx/sched/clock_gettimeofday.d \
./NuttX/nuttx/sched/clock_initialize.d \
./NuttX/nuttx/sched/clock_settime.d \
./NuttX/nuttx/sched/clock_systimer.d \
./NuttX/nuttx/sched/clock_ticks2time.d \
./NuttX/nuttx/sched/clock_time2ticks.d \
./NuttX/nuttx/sched/env_clearenv.d \
./NuttX/nuttx/sched/env_dup.d \
./NuttX/nuttx/sched/env_findvar.d \
./NuttX/nuttx/sched/env_getenv.d \
./NuttX/nuttx/sched/env_getenvironptr.d \
./NuttX/nuttx/sched/env_putenv.d \
./NuttX/nuttx/sched/env_release.d \
./NuttX/nuttx/sched/env_removevar.d \
./NuttX/nuttx/sched/env_setenv.d \
./NuttX/nuttx/sched/env_unsetenv.d \
./NuttX/nuttx/sched/errno_get.d \
./NuttX/nuttx/sched/errno_getptr.d \
./NuttX/nuttx/sched/errno_set.d \
./NuttX/nuttx/sched/exit.d \
./NuttX/nuttx/sched/getpid.d \
./NuttX/nuttx/sched/group_childstatus.d \
./NuttX/nuttx/sched/group_create.d \
./NuttX/nuttx/sched/group_find.d \
./NuttX/nuttx/sched/group_foreachchild.d \
./NuttX/nuttx/sched/group_join.d \
./NuttX/nuttx/sched/group_killchildren.d \
./NuttX/nuttx/sched/group_leave.d \
./NuttX/nuttx/sched/group_setupidlefiles.d \
./NuttX/nuttx/sched/group_setupstreams.d \
./NuttX/nuttx/sched/group_setuptaskfiles.d \
./NuttX/nuttx/sched/group_signal.d \
./NuttX/nuttx/sched/irq_attach.d \
./NuttX/nuttx/sched/irq_dispatch.d \
./NuttX/nuttx/sched/irq_initialize.d \
./NuttX/nuttx/sched/irq_unexpectedisr.d \
./NuttX/nuttx/sched/mq_close.d \
./NuttX/nuttx/sched/mq_descreate.d \
./NuttX/nuttx/sched/mq_findnamed.d \
./NuttX/nuttx/sched/mq_initialize.d \
./NuttX/nuttx/sched/mq_msgfree.d \
./NuttX/nuttx/sched/mq_msgqfree.d \
./NuttX/nuttx/sched/mq_notify.d \
./NuttX/nuttx/sched/mq_open.d \
./NuttX/nuttx/sched/mq_rcvinternal.d \
./NuttX/nuttx/sched/mq_receive.d \
./NuttX/nuttx/sched/mq_recover.d \
./NuttX/nuttx/sched/mq_release.d \
./NuttX/nuttx/sched/mq_send.d \
./NuttX/nuttx/sched/mq_sndinternal.d \
./NuttX/nuttx/sched/mq_timedreceive.d \
./NuttX/nuttx/sched/mq_timedsend.d \
./NuttX/nuttx/sched/mq_unlink.d \
./NuttX/nuttx/sched/mq_waitirq.d \
./NuttX/nuttx/sched/on_exit.d \
./NuttX/nuttx/sched/os_bringup.d \
./NuttX/nuttx/sched/os_start.d \
./NuttX/nuttx/sched/pause.d \
./NuttX/nuttx/sched/pg_miss.d \
./NuttX/nuttx/sched/pg_worker.d \
./NuttX/nuttx/sched/prctl.d \
./NuttX/nuttx/sched/pthread_barrierdestroy.d \
./NuttX/nuttx/sched/pthread_barrierinit.d \
./NuttX/nuttx/sched/pthread_barrierwait.d \
./NuttX/nuttx/sched/pthread_cancel.d \
./NuttX/nuttx/sched/pthread_completejoin.d \
./NuttX/nuttx/sched/pthread_condbroadcast.d \
./NuttX/nuttx/sched/pthread_conddestroy.d \
./NuttX/nuttx/sched/pthread_condinit.d \
./NuttX/nuttx/sched/pthread_condsignal.d \
./NuttX/nuttx/sched/pthread_condtimedwait.d \
./NuttX/nuttx/sched/pthread_condwait.d \
./NuttX/nuttx/sched/pthread_create.d \
./NuttX/nuttx/sched/pthread_detach.d \
./NuttX/nuttx/sched/pthread_exit.d \
./NuttX/nuttx/sched/pthread_findjoininfo.d \
./NuttX/nuttx/sched/pthread_getschedparam.d \
./NuttX/nuttx/sched/pthread_getspecific.d \
./NuttX/nuttx/sched/pthread_initialize.d \
./NuttX/nuttx/sched/pthread_join.d \
./NuttX/nuttx/sched/pthread_keycreate.d \
./NuttX/nuttx/sched/pthread_keydelete.d \
./NuttX/nuttx/sched/pthread_kill.d \
./NuttX/nuttx/sched/pthread_mutexdestroy.d \
./NuttX/nuttx/sched/pthread_mutexinit.d \
./NuttX/nuttx/sched/pthread_mutexlock.d \
./NuttX/nuttx/sched/pthread_mutextrylock.d \
./NuttX/nuttx/sched/pthread_mutexunlock.d \
./NuttX/nuttx/sched/pthread_once.d \
./NuttX/nuttx/sched/pthread_release.d \
./NuttX/nuttx/sched/pthread_setcancelstate.d \
./NuttX/nuttx/sched/pthread_setschedparam.d \
./NuttX/nuttx/sched/pthread_setschedprio.d \
./NuttX/nuttx/sched/pthread_setspecific.d \
./NuttX/nuttx/sched/pthread_sigmask.d \
./NuttX/nuttx/sched/pthread_yield.d \
./NuttX/nuttx/sched/sched_addblocked.d \
./NuttX/nuttx/sched/sched_addprioritized.d \
./NuttX/nuttx/sched/sched_addreadytorun.d \
./NuttX/nuttx/sched/sched_foreach.d \
./NuttX/nuttx/sched/sched_free.d \
./NuttX/nuttx/sched/sched_garbage.d \
./NuttX/nuttx/sched/sched_getfiles.d \
./NuttX/nuttx/sched/sched_getparam.d \
./NuttX/nuttx/sched/sched_getscheduler.d \
./NuttX/nuttx/sched/sched_getsockets.d \
./NuttX/nuttx/sched/sched_getstreams.d \
./NuttX/nuttx/sched/sched_gettcb.d \
./NuttX/nuttx/sched/sched_lock.d \
./NuttX/nuttx/sched/sched_lockcount.d \
./NuttX/nuttx/sched/sched_mergepending.d \
./NuttX/nuttx/sched/sched_processtimer.d \
./NuttX/nuttx/sched/sched_releasetcb.d \
./NuttX/nuttx/sched/sched_removeblocked.d \
./NuttX/nuttx/sched/sched_removereadytorun.d \
./NuttX/nuttx/sched/sched_reprioritize.d \
./NuttX/nuttx/sched/sched_rrgetinterval.d \
./NuttX/nuttx/sched/sched_self.d \
./NuttX/nuttx/sched/sched_setparam.d \
./NuttX/nuttx/sched/sched_setpriority.d \
./NuttX/nuttx/sched/sched_setscheduler.d \
./NuttX/nuttx/sched/sched_unlock.d \
./NuttX/nuttx/sched/sched_verifytcb.d \
./NuttX/nuttx/sched/sched_wait.d \
./NuttX/nuttx/sched/sched_waitid.d \
./NuttX/nuttx/sched/sched_waitpid.d \
./NuttX/nuttx/sched/sched_yield.d \
./NuttX/nuttx/sched/sem_close.d \
./NuttX/nuttx/sched/sem_destroy.d \
./NuttX/nuttx/sched/sem_findnamed.d \
./NuttX/nuttx/sched/sem_holder.d \
./NuttX/nuttx/sched/sem_initialize.d \
./NuttX/nuttx/sched/sem_open.d \
./NuttX/nuttx/sched/sem_post.d \
./NuttX/nuttx/sched/sem_timedwait.d \
./NuttX/nuttx/sched/sem_trywait.d \
./NuttX/nuttx/sched/sem_unlink.d \
./NuttX/nuttx/sched/sem_wait.d \
./NuttX/nuttx/sched/sem_waitirq.d \
./NuttX/nuttx/sched/sig_action.d \
./NuttX/nuttx/sched/sig_allocatependingsigaction.d \
./NuttX/nuttx/sched/sig_cleanup.d \
./NuttX/nuttx/sched/sig_deliver.d \
./NuttX/nuttx/sched/sig_dispatch.d \
./NuttX/nuttx/sched/sig_findaction.d \
./NuttX/nuttx/sched/sig_initialize.d \
./NuttX/nuttx/sched/sig_kill.d \
./NuttX/nuttx/sched/sig_lowest.d \
./NuttX/nuttx/sched/sig_mqnotempty.d \
./NuttX/nuttx/sched/sig_pending.d \
./NuttX/nuttx/sched/sig_procmask.d \
./NuttX/nuttx/sched/sig_queue.d \
./NuttX/nuttx/sched/sig_releasependingsigaction.d \
./NuttX/nuttx/sched/sig_releasependingsignal.d \
./NuttX/nuttx/sched/sig_removependingsignal.d \
./NuttX/nuttx/sched/sig_suspend.d \
./NuttX/nuttx/sched/sig_timedwait.d \
./NuttX/nuttx/sched/sig_unmaskpendingsignal.d \
./NuttX/nuttx/sched/sig_waitinfo.d \
./NuttX/nuttx/sched/sleep.d \
./NuttX/nuttx/sched/task_activate.d \
./NuttX/nuttx/sched/task_create.d \
./NuttX/nuttx/sched/task_delete.d \
./NuttX/nuttx/sched/task_exit.d \
./NuttX/nuttx/sched/task_exithook.d \
./NuttX/nuttx/sched/task_getgroup.d \
./NuttX/nuttx/sched/task_init.d \
./NuttX/nuttx/sched/task_posixspawn.d \
./NuttX/nuttx/sched/task_recover.d \
./NuttX/nuttx/sched/task_reparent.d \
./NuttX/nuttx/sched/task_restart.d \
./NuttX/nuttx/sched/task_setup.d \
./NuttX/nuttx/sched/task_spawn.d \
./NuttX/nuttx/sched/task_spawnparms.d \
./NuttX/nuttx/sched/task_start.d \
./NuttX/nuttx/sched/task_starthook.d \
./NuttX/nuttx/sched/task_terminate.d \
./NuttX/nuttx/sched/task_vfork.d \
./NuttX/nuttx/sched/timer_create.d \
./NuttX/nuttx/sched/timer_delete.d \
./NuttX/nuttx/sched/timer_getoverrun.d \
./NuttX/nuttx/sched/timer_gettime.d \
./NuttX/nuttx/sched/timer_initialize.d \
./NuttX/nuttx/sched/timer_release.d \
./NuttX/nuttx/sched/timer_settime.d \
./NuttX/nuttx/sched/usleep.d \
./NuttX/nuttx/sched/wd_cancel.d \
./NuttX/nuttx/sched/wd_create.d \
./NuttX/nuttx/sched/wd_delete.d \
./NuttX/nuttx/sched/wd_gettime.d \
./NuttX/nuttx/sched/wd_initialize.d \
./NuttX/nuttx/sched/wd_start.d 


# Each subdirectory must supply rules for building sources it contributes
NuttX/nuttx/sched/%.o: ../NuttX/nuttx/sched/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


